another update to the .yml file

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -62,42 +62,22 @@ jobs:
 
       - name: 📥 Download APK
         env:
-          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
+        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
         run: |
           mkdir -p dist
 
           eas build:download \
-            --build-id "${{ steps.build-info.outputs.BUILD_ID }}" \
-            --non-interactive \
-            --output dist/app-release.apk
+          --build-id "${{ steps.build-info.outputs.BUILD_ID }}" \
+          --non-interactive \
+          --path dist/app-release.apk
 
           if [ ! -f dist/app-release.apk ]; then
-            echo "❌ APK was not found"
-            exit 1
+          echo "❌ APK was not found"
+          exit 1
           fi
 
           echo "✅ APK found: dist/app-release.apk"
 
-      # - name: 📥 Download APK
-      #   env:
-      #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
-      #   run: |
-      #     mkdir -p dist
-
-      #     eas build:download \
-      #       --build-id "${{ steps.build-info.outputs.BUILD_ID }}" \
-      #       --non-interactive
-
-      #     APK=$(find . -type f -name "*.apk" | head -n 1)
-
-      #     if [ -z "$APK" ]; then
-      #       echo "❌ APK was not found"
-      #       exit 1
-      #     fi
-
-      #     echo "✅ APK found: $APK"
-
-      #     cp "$APK" dist/app-release.apk
 
       - name: 🏷️ Generate release tag
         id: release
